# Syntax highlighting
# -------------------
# -- Misc
"comment" = { fg = "overlay1", modifiers = ["italic"] }
"operator" = { fg = "sky" }

# -- Punctuation
"punctuation.delimiter" = { fg = "overlay2"}
"punctuation.bracket" = { fg = "overlay2"}
"punctuation.special" = { fg = "sky" }

# -- Literals
"string" = { fg = "green" }
"string.regex" = { fg = "peach" }
"string.escape" = { fg = "pink" }
"string.special" = { fg = "blue"}

"character" = { fg = "teal" }

"boolean" = { fg = "peach" }
"number" = { fg = "peach" }
"float" = { fg = "peach" }

# -- Functions
"function" = { fg = "blue" }
"function.builtin" = { fg = "peach" }
"function.call" = {fg = "blue" }
"function.macro" = { fg = "teal" }
"method" = { fg = "blue" }

"method.call" = { fg = "blue" }

"constructor" = { fg = "sapphire" }
"parameter" = { fg = "maroon", modifiers = ["italic"] }

# -- Keywords
"keyword" = { fg = "mauve" }
"keyword.function" = { fg = "mauve" }
"keyword.operator" = { fg = "mauve" }
"keyword.return" = { fg = "mauve" }

# -- JS & derivative
"keyword.export" = { fg = "sky", modifiers = ["bold"] }

"conditional" = { fg = "mauve", modifiers = ["italic"] }
"repeat" = { fg = "mauve" }

"exception" = { fg = "mauve" }

# -- Types

"type" = { fg = "yellow" }
"type.builtin" = { fg = "yellow", modifiers = ["italic"] }
"type.definition" = { fg = "yellow" }
"type.qualifier" = { fg  ="yellow" }

# "attribute" = { link = "Constant" }
"field" = { fg = "teal"}
"property" = { fg = "teal" }

# -- Identifiers

"variable" = { fg = "text" }
"variable.builtin" = { fg = "red"}

"constant" = { fg = "peach"}
"constant.builtin" = { fg = "peach"}
"constant.macro" = { fg = "teal" }

"namespace" = { fg = "blue", modifiers = ["italic"] }
"symbol" = { fg = "flamingo"}

# -- Text

"text" = { fg = "text"}
"text.strong" = { fg = "maroon", modifiers = ["bold"] }
"text.emphasis" = { fg = "maroon", modifiers = ["italic"] }
"text.strike" = { fg = "text" }
"text.title" = { fg = "blue", modifiers = ["bold"] }
"text.literal" = { fg = "teal"}
"text.uri" = { fg = "rosewater", modifiers = ["italic"]}
"text.math" = { fg = "blue"}
"text.environment" = { fg = "pink"}
"text.environment.name" = { fg = "blue"}
"text.reference" = { fg = "lavender", modifiers = ["bold"] }

"text.todo" = { fg = "base", bg = "yellow"}
"text.todo.checked" = { fg = "green"}
"text.todo.unchecked" = { fg = "overlay1"}
"text.note" = { fg = "base", bg = "blue"}
"text.warning" = { fg = "base", bg = "yellow"}
"text.danger" = { fg = "base", bg = "red"}


# -- Tags
"tag" = { fg = "mauve"}
"tag.attribute" = { fg = "teal", modifiers = ["italic"] }
"tag.delimiter" = { fg = "sky" }

# -- Language specific:

# -- css
"property.css" = { fg = "lavender"}
"property.id.css" = { fg = "blue"}
"property.class.css" = { fg = "yellow"}
"type.css" = { fg = "lavender"}
"type.tag.css" = { fg = "mauve"}
"string.plain.css" = { fg = "peach"}
"number.css" = { fg = "peach"}

# -- toml
"property.toml" = { fg = "blue"}

# -- json
"label.json" = { fg = "blue"}

# -- lua
"field.lua" = { fg = "lavender"}
"constructor.lua" = { fg = "flamingo"}

# -- typescript
"constructor.typescript" = { fg = "lavender"}

# -- TSX (Typescript React)
"constructor.tsx" = { fg = "lavender"}
"tag.attribute.tsx" = { fg = "mauve"}

# -- yaml
"field.yaml" = { fg = "blue"}

# -- Ruby
"symbol.ruby" = { fg = "flamingo"}

# -- PHP
"type.qualifier.php" = { fg = "pink" }
# User Interface
# --------------
"ui.background" = { fg = "text", bg = "base" }
"ui.text" = "text" 

[palette]
# catppuccin palette colors
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"

text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"

base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

# derived colors by blending existing palette colors
cursorline = "#e9ebf1"
secondary_cursor = "#e2a99e"
