
"annotation" = {fg = "fg"}
"attribute" = {fg = "cyan"}
"boolean" = {fg = "orange"}
"character" = {fg = "orange"}
"comment" = {fg = "grey", modifiers = ["italic"] }
"conditional" = {fg = "purple" }
"constant" = {fg = "orange" }
"constant.builtin" = {fg = "orange" }
"constant.macro" = {fg = "orange" }
"constructor" = {fg = "yellow", modifiers = [] }
"error" = {fg = "fg" }
"exception" = {fg = "purple" }
"field" = {fg = "cyan" }
"float" = {fg = "orange" }
"function" = {fg = "blue", modifiers = ["italic"] }
"function.builtin" = {fg = "cyan", modifiers = [] }
"function.macro" = {fg = "cyan", modifiers = [] }
"include" = {fg = "purple" }
"keyword" = {fg = "purple", modifiers = [] }
"keyword.function" = {fg = "purple", modifiers = [] }
"keyword.operator" =  {fg = "purple", modifiers = [] }
"label" = {fg = "red" }
"method" = {fg = "blue" }
"namespace" = {fg = "yellow" }
"none" = {fg = "fg" }
"number" = {fg = "orange" }
"operator" = {fg = "fg" }
"parameter" = {fg = "red" }
"parameter.reference" = {fg = "fg" }
"property" = {fg = "cyan" }
"punctuation.delimiter" = {fg = "light_grey" }
"punctuation.bracket" = {fg = "light_grey" }
"punctuation.special" = {fg = "red" }
"repeat" = {fg = "purple", modifiers = [] }
"string" = {fg = "green", modifiers = [] }
"string.regex" = {fg = "orange", modifiers = [] }
"string.escape" = {fg = "red", modifiers = [] }
"symbol" = {fg = "cyan" }
"tag" = {fg = "red" }
"tag.delimiter" = {fg = "red" }
"text" = {fg = "fg" }
"text.strong" = {fg = "fg", modifiers = ["bold"] }
"text.emphasis" = {fg = "fg", modifiers = ["italic"] }
"text.underline" = {fg = "fg", modifiers = ["underline"] }
"text.strike" = {fg = "fg", modifiers = ["strikethrough"] }
"text.title" = {fg = "orange", modifiers = ["bold"] }
"text.literal" = {fg = "green" }
"text.uri" = {fg = "cyan", modifiers = ["underline"] }
"text.math" = {fg = "fg" }
"text.reference" = {fg = "blue" }
"text.enviroment" = {fg = "fg" }
"text.enviroment.name" = {fg = "fg" }
"note" = {fg = "fg" }
"warning" = {fg = "fg" }
"danger" = {fg = "fg" }
"type" = {fg = "yellow" }
"type.builtin" = {fg = "orange" }
"variable" = {fg = "red", modifiers = [] }
"variable.builtin" = {fg = "red", modifiers = [] }

"ui.background" = {bg = "black" }
"ui.text" = { fg = "fg" }

[palette]
black = "#181a1f"
bg0 = "#282c34"
bg1 = "#31353f"
bg2 = "#393f4a"
bg3 = "#3b3f4c"
bg_d = "#21252b"
bg_blue = "#73b8f1"
bg_yellow = "#ebd09c"
fg = "#abb2bf"
purple = "#c678dd"
green = "#98c379"
orange = "#d19a66"
blue = "#61afef"
yellow = "#e5c07b"
cyan = "#56b6c2"
red = "#e86671"
grey = "#5c6370"
light_grey = "#848b98"
dark_cyan = "#2b6f77"
dark_red = "#993939"
dark_yellow = "#93691d"
dark_purple = "#8a3fa0"
diff_add = "#31392b"
diff_delete = "#382b2c"
diff_change = "#1c3448"
diff_text = "#2c5372"
