[package]
name = "gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.9.2"
tree-painter = { path = "../tree-painter/", default-features = false, features = ["tree-sitter-rust", "tree-sitter-c", "tree-sitter-cpp", "tree-sitter-java", "tree-sitter-css"] }
titlecase = "2.2.1"
regex  = "1.7.0"
dateparser = "0.1.7"
fs_extra = "1.2.0"
handlebars = "4.3.5"
serde = {version = "1.0.149", features = ["derive"]}
# tree-painter = {version="0", default-features = false, features = ["tree-sitter-rust", "tree-sitter-c", "tree-sitter-cpp"] }
